name: Update README Structure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install tree
        run: |
          # Install tree if not already available
          sudo apt-get install -y tree || true

      - name: Generate directory structure
        run: |
          # Generate the structure, save to a temp file
          ls -al
          tree -I ".git|.github|__pycache__|.idea" > repo_structure.txt || true
          
          # Verify the output file exists and display its content for debugging
          if [ -s repo_structure.txt ]; then
            echo "Directory structure generated successfully:"
            cat repo_structure.txt
          else
            echo "Failed to generate directory structure" >&2
            exit 1
          fi

      - name: Update README
        run: |
          # Update the README file with the new structure.
          awk '/## Repository Structure/{flag=1;print;print "```plaintext";system("cat repo_structure.txt");print "```";next} /```/{flag=0} !flag' README.md > updated_README.md
          mv updated_README.md README.md

      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name "ekwest11"
          git config --local user.email "ekwest11@gmail.com"
          git add README.md
          git commit -m "Auto-update README with latest directory structure" || echo "No changes to commit"
          git push "https://$PAT_TOKEN@github.com/ekwest11/pattern_practice.git" HEAD:main
