name: Update README Structure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install tree
        run: |
          # Install tree if not already available
          sudo apt-get install -y tree || true

      - name: Generate directory structure
        run: |
          # Generate the structure, saving to a temp file in /tmp to avoid including it in the README structure
          ls -al
          tree -I ".git|.github|__pycache__|.idea" > /tmp/repo_structure.txt || true

          # Verify the output file exists and display its content for debugging
          if [ -s /tmp/repo_structure.txt ]; then
            echo "Directory structure generated successfully:"
            cat /tmp/repo_structure.txt
          else
            echo "Failed to generate directory structure" >&2
            exit 1
          fi

        run: |
          # Use awk to replace the "Repository Structure" section cleanly
          awk '
            BEGIN { flag = 0 }
            /## Repository Structure/ { 
              flag = 1
              print "## Repository Structure\n```plaintext"
              system("cat /tmp/repo_structure.txt")
              print "```"
              next 
            }
            flag && /```/ { flag = 0 }
            !flag
          ' README.md > updated_README.md
          mv updated_README.md README.md
          rm /tmp/repo_structure.txt  # Clean up the temporary file

      - name: Commit Changes to a New Branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-readme-structure
          git add README.md
          git commit -m "Auto-update README with latest directory structure" || echo "No changes to commit"
          git push --force "https://$PAT_TOKEN@github.com/ekwest11/pattern_practice.git" update-readme-structure

      - name: Check for Existing Pull Request
        id: find_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:update-readme-structure`,
              base: 'main'
            });
            return pulls.data.length > 0 ? pulls.data[0].html_url : null;

      - name: Create Pull Request
        if: steps.find_pr.outputs.result == 'null'  # Only create if no existing PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'update-readme-structure',
              base: 'main',
              title: 'Auto-update README with latest directory structure',
              body: 'This PR was created automatically by a GitHub Action to update the README structure.',
            });
            console.log(`Pull request created: ${pullRequest.html_url}`);