name: Update README Structure

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Directory Structure
        run: |
          # Install tree if not already available
          sudo apt-get update && sudo apt-get install -y tree
          # Generate the structure, save to a temp file
          tree -I ".git|.github|__pycache__" pattern_practice/ > repo_structure.txt

      - name: Update README
        run: |
          # Update the README file with the new structure
          awk '/## Repository Structure/{flag=1;print;print "```plaintext";system("cat repo_structure.txt");print "```";next} /```/{flag=0} !flag' README.md > updated_README.md
          mv updated_README.md README.md

      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add README.md
          git commit -m "Auto-update README with latest directory structure" || echo "No changes to commit"
          git push "https://$PAT_TOKEN@github.com/ekwest11/pattern_practice.git" HEAD:main
